services:
  - type: web
    name: messenger-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn messenger_api:app --host 0.0.0.0 --port $PORT"